name: PR build

on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-build-caller-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  pull-requests: write
  checks: write

jobs:
  pr-build:
    uses: hwinther/reusable-workflows/.github/workflows/pr-build.yml@v2
    with:
      node_enabled: true
      node_version: "24.x"
      node_working_directory: "."
      node_changes_regex: ".*"
      node_registry_url: "https://registry.npmjs.org"
      node_test_enabled: true
